name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies package json
    - run: npm run install

    - name: Display name
    - run: echo georgilukanov

    - name: Run unit tests
    - run: npm run test:unit
